### ISSUE TITLE
Is there a way to sign-out using Discord?

### ISSUE THREAD

**Issue by gk0r** [nicholastay/passport-discord#16]
Hi team

I offer my users a functionality to link their Discord credentials to their user accounts. I would also like to offer them the ability to change their Discord credentials. Is there a way I could sign-out from one account, and give them an option to sign-in with a different account?

Thanks!

**Comment by ArnaultNouvel** [comment]
Hello

Same issue here, some users have 2 discord accounts and cannot switch account after loging out from my app because cookies are kept on https://discordapp.com. 
User remains logged in there, so when he wants to login again, he lands directly on the "Authorize" page without ability to switch account.

Would be nice if user could switch account from the "authorize" page, or if a "destroy session" url was provided to us developers, so we could redirect users there after loging them out from our app.

**Comment by SayakMukhopadhyay** [comment]
I think this is the wrong place for this request. This feature needs to implemented on Discord side. This is a client side library.

**Comment by PLASMAchicken** [comment]
Discord does not support one Person having two Accounts, so this wont be really a feature they will implement.

**Comment by gk0r** [comment]
Right. Closing the issue
